In [9]:
import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

#Load from CSV
df = pd.read_csv("Iris.csv")

# change
pathX = df.iloc[:, :-1].values

# All columns except last → Features
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Last column only → Target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.2, random_state=42)

# KNN model
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# Predictions & accuracy
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy (CSV iris) with k={k}: {accuracy:.2f}")



Accuracy (CSV iris) with k=3: 1.00


In [13]:
from sklearn.metrics import confusion_matrix

# confusion matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

#prediction :  Provide a sample with 5 features (e.g., using the first row from pathX)
new_data = pathX[0].reshape(1, -1)
prediction = knn.predict(new_data)
print(f"Prediction for {new_data}: {prediction}")


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Prediction for [[1.  5.1 3.5 1.4 0.2]]: ['Iris-setosa']
